CREATE TABLE IF NOT EXISTS users(
    id BIGINT AUTO_INCREMENT,
    name VARCHAR(150) NOT NULL,
    email  VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(200) NOT NULL,
    type VARCHAR(30) NOT NULL,
    PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;